import {Inter} from 'next/font/google'
import './globals.css'
import NextUI_Provider from "@/app/NextUiProvider";
import SidebarAdmin from "@/components/Table/SidebarAdmin";

const inter = Inter({subsets: ['latin']})
import Providers from "@/store/Providers";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="bg-background-color">
        <Providers>
            <NextUI_Provider>
                <SidebarAdmin/>
                {children}
            </NextUI_Provider>
        </Providers>
        </body>
        </html>
    )}
// export default function RootLayout({ children }) {
//         return (
//             <html lang="en">
//             <body className="bg-background-color">
//             <NextUI_Provider>
//                 <SidebarAdmin/>
//                 <div className='pl-[15%] py-14'>
//                     {children}
//                 </div>
//             </NextUI_Provider>
//             </body>
//             </html>
//         )
//     }
